name: boutique_mobile
description: A minimal debt manager demo
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.6.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  cached_network_image: ^3.2.3
  flutter_svg: ^2.2.3
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  connectivity_plus: ^7.0.0
  audioplayers: ^6.5.1
  uuid: ^4.5.2
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  google_fonts: ^6.3.2
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1
  url_launcher: ^6.3.2
  web: ^1.1.1
  pdf: ^3.10.0
  share_plus: ^12.0.1
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  sentry_flutter: ^9.8.0

  crypto: any
  flutter_dotenv: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.svg
