name: boutique_mobile
description: A minimal debt manager demo
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.6.0
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
